// Developer portfolio content (portfolio.html). Every text has th / en versions.
// Freelance page content lives in js/content.js.

const PORTFOLIO_I18N = {
  th: {
    "meta.title": "F1lmw8 | Developer Portfolio",
    "meta.desc": "พอร์ตโฟลิโอของ F1lmw8 นักศึกษาวิทยาการคอมพิวเตอร์ มหาวิทยาลัยแม่โจ้ Full-Stack Developer ผลงานด้าน HealthTech, Cloud และ AI",
    "nav.home": "หน้าแรก",
    "nav.about": "เกี่ยวกับ",
    "nav.skills": "ทักษะ",
    "nav.projects": "โปรเจค",
    "nav.contact": "ติดต่อ",
    "nav.hire": "จ้างงาน",
    "nav.terminal": "เปิด Terminal",
    "nav.theme": "สลับธีม",
    "nav.menu": "เมนู",
    "lang.switch": "Switch to English",

    "hero.tag": "เปิดรับงานและโอกาสใหม่ ๆ",
    "hero.title": "สร้างซอฟต์แวร์ที่ใช้งานได้จริงในชื่อ",
    "hero.subtitle.pre": "ผมเป็น",
    "hero.subtitle.post": "ที่สร้างเว็บแอปแบบ full-stack เครื่องมือ HealthTech สำหรับร้านยา และระบบที่ใช้ AI ช่วยงาน",
    "hero.explore": "ดูโปรเจค",
    "hero.hire": "จ้างงาน / ราคา",
    "hero.github": "GitHub",
    "hero.role": "CS Student · Full-Stack Developer",
    "hero.stat1": "Repos",
    "hero.stat2": "เดโมออนไลน์",
    "hero.stat3": "วิทยาการคอมฯ",

    "about.sub": "// ประวัติ",
    "about.title": "เกี่ยวกับ & ประสบการณ์",
    "about.desc": "ชอบโค้ดที่เป็นระเบียบ UI ที่ใช้ง่าย และเทคโนโลยี AI ใหม่ ๆ",
    "about.cardTitle": "สร้างซอฟต์แวร์สำหรับโลกจริง",
    "about.body": "สวัสดีครับ ผมชื่อ ฟิล์ม นักศึกษาสาขาวิทยาการคอมพิวเตอร์ มหาวิทยาลัยแม่โจ้ ผมสร้างเว็บแอปครบวงจร ตั้งแต่ระบบขายหน้าร้านร้านยา ระบบฉลากยา ไปจนถึงเกมฝึกตรรกะ และชอบเชื่อมระบบเข้ากับข้อมูลจริง บริการคลาวด์ และ AI โปรเจคจบของผมคือ Chalakya ระบบฉลากยาที่ใช้งานจริงที่ chalakya.in.th",
    "about.h1.title": "AI Integration", "about.h1.desc": "LLM tool-calling, Gemini",
    "about.h2.title": "Full-Stack", "about.h2.desc": "Next.js, Vue, Express, FastAPI",
    "about.h3.title": "Cloud & DevOps", "about.h3.desc": "Docker, gRPC, Vercel, Render",
    "about.h4.title": "HealthTech", "about.h4.desc": "ระบบ POS และฉลากยา",
    "about.timeline": "เส้นทาง",
    "about.t1.date": "2026",
    "about.t1.title": "โปรเจคจบ — Chalakya ระบบฉลากยา",
    "about.t1.desc": "พิมพ์ฉลากยา 3 ภาษา ส่งฉลากดิจิทัลผ่าน LINE OA ต่อยอดจาก prototype ระบบ POS ร้านยาที่มี AI ผู้ช่วยเภสัชกร",
    "about.t2.date": "2025 - 2026",
    "about.t2.title": "Cloud & DevOps",
    "about.t2.company": "วิทยาการคอมพิวเตอร์ มหาวิทยาลัยแม่โจ้",
    "about.t2.desc": "ทำ microservices ด้วย FastAPI และ gRPC บน Docker และ deploy แอป full-stack (Express, Prisma, Supabase, Quasar) ขึ้น Render และ Netlify",
    "about.t3.date": "2023 - ปัจจุบัน",
    "about.t3.title": "วท.บ. วิทยาการคอมพิวเตอร์",
    "about.t3.company": "มหาวิทยาลัยแม่โจ้ เชียงใหม่",
    "about.t3.desc": "เรียนการพัฒนาซอฟต์แวร์ เว็บ ฐานข้อมูล และคลาวด์ พร้อมทำโปรเจคเว็บจริงหลายชิ้น",

    "skills.sub": "// ความสามารถ",
    "skills.title": "ทักษะทางเทคนิค",
    "skills.desc": "เทคโนโลยีและเฟรมเวิร์กที่ใช้สร้างซอฟต์แวร์",
    "skills.all": "ทั้งหมด",
    "skills.frontend": "Frontend",
    "skills.backend": "Backend",
    "skills.ai": "AI",
    "skills.tools": "DevOps & Tools",
    "skills.level": "ความชำนาญ",

    "projects.sub": "// ผลงาน",
    "projects.title": "โปรเจคเด่น",
    "projects.desc": "ตัวอย่างงานที่พัฒนาจริง ทั้งเว็บแอป ระบบหลังบ้าน และเกม",
    "projects.all": "ทั้งหมด",
    "projects.ai": "AI",
    "projects.web": "เว็บแอป",
    "projects.devops": "Backend & DevOps",
    "projects.game": "เกม",
    "projects.details": "รายละเอียด",
    "projects.code": "โค้ด",
    "projects.visit": "เข้าเว็บ",
    "projects.demo": "ดูเดโม",
    "projects.source": "ซอร์สโค้ด",
    "projects.live": "🟢 ออนไลน์",
    "projects.sourceOnly": "📦 มีซอร์สโค้ด",
    "projects.private": "📂 ขอดูโค้ดได้",

    "contact.sub": "// ติดต่อ",
    "contact.title": "มาคุยกันได้",
    "contact.desc": "มีโปรเจคในใจ มีคำถาม หรืออยากร่วมงาน ทักมาได้เลย",
    "contact.reach": "ช่องทางติดต่อ",
    "contact.reachDesc": "ยินดีคุยเรื่องโปรเจคใหม่ ไอเดีย หรือความร่วมมือทางเทคนิค ถ้าต้องการจ้างทำเว็บ ดูแพ็กเกจและราคาได้ที่หน้ารับงาน",
    "contact.copy": "คัดลอกอีเมล",
    "contact.copied": "คัดลอกอีเมลแล้ว",
    "contact.hireTitle": "ต้องการจ้างทำเว็บหรือแอป?",
    "contact.hireDesc": "ดูแพ็กเกจเริ่มต้น 5,000 บาท ขั้นตอนการทำงาน และช่องทาง LINE / Facebook ได้ที่หน้ารับงาน",
    "contact.hireBtn": "ไปที่หน้ารับงาน",

    "footer.note": "Hosted on GitHub Pages",
    "toast.theme": "เปลี่ยนธีมแล้ว",
  },

  en: {
    "meta.title": "F1lmw8 | Developer Portfolio",
    "meta.desc": "Portfolio of F1lmw8 - Computer Science student at Maejo University and full-stack developer working on HealthTech, cloud, and AI projects.",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.contact": "Contact",
    "nav.hire": "Hire me",
    "nav.terminal": "Open terminal",
    "nav.theme": "Toggle theme",
    "nav.menu": "Menu",
    "lang.switch": "เปลี่ยนเป็นภาษาไทย",

    "hero.tag": "Available for new opportunities",
    "hero.title": "Building real-world software as",
    "hero.subtitle.pre": "I am a",
    "hero.subtitle.post": "building full-stack web apps, HealthTech tools for pharmacies, and AI-assisted systems.",
    "hero.explore": "Explore projects",
    "hero.hire": "Hire me / Pricing",
    "hero.github": "GitHub",
    "hero.role": "CS Student · Full-Stack Developer",
    "hero.stat1": "Repos",
    "hero.stat2": "Live demos",
    "hero.stat3": "Comp. Sci.",

    "about.sub": "// Biography",
    "about.title": "About & Experience",
    "about.desc": "Passionate about clean code, intuitive interfaces, and emerging AI technologies.",
    "about.cardTitle": "Building Real-World Software",
    "about.body": "Hello! My name is Film, a Computer Science student at Maejo University. I build end-to-end web applications — from pharmacy POS and labeling systems to learning games — and I enjoy connecting them to real data, cloud services, and AI. My senior project, Chalakya, is a pharmacy label system that is live at chalakya.in.th.",
    "about.h1.title": "AI Integration", "about.h1.desc": "LLM tool-calling, Gemini",
    "about.h2.title": "Full-Stack", "about.h2.desc": "Next.js, Vue, Express, FastAPI",
    "about.h3.title": "Cloud & DevOps", "about.h3.desc": "Docker, gRPC, Vercel, Render",
    "about.h4.title": "HealthTech", "about.h4.desc": "Pharmacy POS & labeling",
    "about.timeline": "Milestones",
    "about.t1.date": "2026",
    "about.t1.title": "Senior Project — Chalakya Pharmacy Label System",
    "about.t1.desc": "Tri-lingual prescription label printing with LINE OA digital labels, built after prototyping a full pharmacy POS with an AI clinical assistant.",
    "about.t2.date": "2025 - 2026",
    "about.t2.title": "Cloud & DevOps",
    "about.t2.company": "Computer Science, Maejo University",
    "about.t2.desc": "Dockerised microservices with FastAPI and gRPC, and deployed full-stack apps (Express, Prisma, Supabase, Quasar) to Render and Netlify.",
    "about.t3.date": "2023 - PRESENT",
    "about.t3.title": "B.Sc. Computer Science",
    "about.t3.company": "Maejo University, Chiang Mai",
    "about.t3.desc": "Studying software development, web technologies, databases, and cloud computing, with many hands-on web projects along the way.",

    "skills.sub": "// Capabilities",
    "skills.title": "Technical Expertise",
    "skills.desc": "Technologies and frameworks I use to build software.",
    "skills.all": "All Skills",
    "skills.frontend": "Frontend",
    "skills.backend": "Backend",
    "skills.ai": "AI",
    "skills.tools": "DevOps & Tools",
    "skills.level": "Proficiency",

    "projects.sub": "// Showcase",
    "projects.title": "Featured Projects",
    "projects.desc": "Real work I have built: web apps, back-end systems, and games.",
    "projects.all": "All Projects",
    "projects.ai": "AI",
    "projects.web": "Web Apps",
    "projects.devops": "Backend & DevOps",
    "projects.game": "Games",
    "projects.details": "Details",
    "projects.code": "Code",
    "projects.visit": "Visit Site",
    "projects.demo": "Live Demo",
    "projects.source": "Source Code",
    "projects.live": "🟢 Live",
    "projects.sourceOnly": "📦 Source available",
    "projects.private": "📂 Code on request",

    "contact.sub": "// Get In Touch",
    "contact.title": "Let's Connect",
    "contact.desc": "Have a project in mind, a question, or want to collaborate? Reach out!",
    "contact.reach": "Reach Out",
    "contact.reachDesc": "I am always open to discussing new projects, ideas, or technical collaborations. Looking to hire me for a website? See packages and pricing on the services page.",
    "contact.copy": "Copy Email Address",
    "contact.copied": "Email copied to clipboard!",
    "contact.hireTitle": "Need a website or app built?",
    "contact.hireDesc": "See the starter package from 5,000 THB, how I work, and LINE / Facebook contacts on the services page.",
    "contact.hireBtn": "Go to services page",

    "footer.note": "Hosted on GitHub Pages",
    "toast.theme": "Theme switched",
  },
};

const TYPING_WORDS = {
  th: ["นักศึกษาวิทยาการคอมพิวเตอร์", "Full-Stack Developer", "นักพัฒนา HealthTech", "ผู้หลงใหล AI"],
  en: ["Computer Science Student", "Full-Stack Developer", "HealthTech Builder", "AI Enthusiast"],
};

const PROJECTS_DATA = [
  {
    id: "project-pharmacy",
    title: "Chalakya — Pharmacy Label & LINE OA System",
    category: "web",
    categoryLabel: { th: "โปรเจคจบ", en: "Senior Project" },
    image: "assets/images/project-pharmacy.jpg",
    description: {
      th: "เครื่องพิมพ์ฉลากยาอัจฉริยะ 3 ภาษา (ไทย/อังกฤษ/จีน) พร้อมบาร์โค้ด ส่งฉลากดิจิทัลผ่าน LINE OA และทะเบียนผู้ป่วยตาม PDPA",
      en: "Tri-lingual (TH/EN/ZH) smart prescription label printer with barcode generation, LINE OA digital label delivery, and a PDPA-compliant patient registry.",
    },
    fullDescription: {
      th: "โปรเจคจบที่มหาวิทยาลัยแม่โจ้ ใช้งานจริงที่ chalakya.in.th เป็นชุดเครื่องมือสำหรับร้านขายยา พิมพ์สติกเกอร์ฉลากยาแบบ WYSIWYG พร้อมบาร์โค้ด Code 128 ประกอบวิธีใช้ยาได้ 3 ภาษา ส่งฉลากดิจิทัลผ่าน LINE Official Account ด้วย Vercel Serverless ซิงก์ข้อมูลบน Supabase นำเข้าฐานข้อมูลยาจาก Excel ด้วย SheetJS และมีแบบฟอร์มขอความยินยอมตาม PDPA",
      en: "My senior (capstone) project at Maejo University, live at chalakya.in.th. A pharmacy workflow suite built for retail drugstores. Features WYSIWYG sticker printing with Code 128 barcodes, multi-language dosage assembly (Thai, English, Chinese), LINE Official Account digital label dispatch via Vercel Serverless, Supabase cloud syncing, SheetJS Excel master drug import, and PDPA-compliant digital consent forms.",
    },
    tags: ["JavaScript", "LINE LIFF", "Supabase", "Vercel Serverless", "SheetJS", "LINE Messaging API"],
    year: "2026",
    demoUrl: "https://chalakya.in.th",
  },
  {
    id: "project-rdu-pos",
    title: "RDU Pharmacy POS & AI Clinical Agent (Prototype)",
    category: "ai",
    categoryLabel: { th: "AI & HealthTech", en: "AI & HealthTech" },
    image: "assets/images/covers/rdu-pos.svg",
    description: {
      th: "ระบบขายหน้าร้านร้านยา ค้นหาข้อมูล RDU แดชบอร์ดสต็อกและยอดขาย ชำระเงินด้วย PromptPay QR และ AI agent ที่อ้างอิงข้อมูลจาก RxNorm และ openFDA",
      en: "Pharmacy point-of-sale with Rational Drug Use (RDU) lookup, stock & sales dashboards, PromptPay QR checkout, and a tool-calling AI agent grounded on RxNorm and openFDA.",
    },
    fullDescription: {
      th: "Prototype แรกของโปรเจคจบ ทำระบบ POS ร้านยาไปราว 40–50% ก่อนเปลี่ยนหัวข้อเป็นระบบฉลากยา (Chalakya) แต่ฟีเจอร์ที่ทำเสร็จใช้งานได้จริง เป็นระบบ Next.js 15 สำหรับร้านยาไทย ค้นหายาด้วยชื่อไทยหรืออังกฤษ ดูข้อมูล RDU และเอกสารกำกับยา ขายพร้อม PromptPay QR จัดการสต็อกแยกล็อตแบบ FEFO รับสินค้า (GRN) รายงาน GPP ข.ย. 9/10/11 แจ้งเตือนแพ้ยา ออกใบกำกับภาษีตาม ม.86 และส่งออก Excel บน PostgreSQL มี AI ผู้ช่วยเภสัชกร (Vercel AI SDK + Gemini) ที่ดึงข้อมูลจาก RxNorm และ openFDA และตอบจากข้อมูลทางการเท่านั้น",
      en: "The first prototype of my senior project — about 40–50% of a full pharmacy POS was built before the project pivoted to the Pharmacy Label System (Chalakya), but the completed features are fully working. A Next.js 15 App Router system for Thai drugstores: search drugs by Thai or English name, view RDU details and leaflets, sell with PromptPay QR payment, and manage lot-based FEFO stock, goods receipts, GPP reports (ข.ย. 9/10/11), patient allergy alerts, and Section 86 tax invoices with Excel export, backed by PostgreSQL. A built-in AI assistant (Vercel AI SDK + Gemini) calls RxNorm and openFDA tools and answers only from official FDA data.",
    },
    tags: ["Next.js 15", "React 19", "PostgreSQL", "Vercel AI SDK", "Gemini", "openFDA", "Recharts", "PromptPay QR"],
    year: "2026",
    demoUrl: "https://medpos-tech.vercel.app",
    githubUrl: "https://github.com/F1lmw8/Pos_project",
  },
  {
    id: "project-nocode-adventure",
    title: "No-Code Adventure — Logic Puzzle Game",
    category: "game",
    categoryLabel: { th: "เกมการศึกษา", en: "EdTech Game" },
    image: "assets/images/covers/nocode.svg",
    description: {
      th: "เกมบนเว็บสอนตรรกะการเขียนโปรแกรมสำหรับมือใหม่ ต่อบล็อกคำสั่งเดิน เลี้ยว เงื่อนไข และลูป พาตัวละครผ่านด่านจนถึงบอส",
      en: "Browser game that teaches programming logic to beginners: stack Move, Turn, Condition, and Loop blocks to guide a character through grid levels up to a boss stage.",
    },
    fullDescription: {
      th: "เกม HTML/CSS/JavaScript ไฟล์เดียวไม่พึ่งไลบรารี ออกแบบให้มือใหม่ฝึกคิดแบบโปรแกรมเมอร์ ผู้เล่นต่อบล็อกคำสั่งตามสี (เดิน เลี้ยว เงื่อนไข ลูป) แล้วกดรันดูตัวละครทำงานทีละขั้นบนแผนที่ ด่านยากขึ้นเรื่อย ๆ จนถึงด่านบอส และให้ดาวตามความกระชับของโค้ด deploy บน Vercel",
      en: "A single-file, dependency-free HTML/CSS/JavaScript game designed for beginners learning to think like programmers. Players build a program from colour-coded command blocks (move, turn, if-conditions, loops), run it, and watch the character execute step by step on a grid map. Levels ramp up in difficulty and finish with a boss stage, with star ratings for efficient solutions. Deployed on Vercel.",
    },
    tags: ["HTML5", "CSS3", "Vanilla JavaScript", "Game Design", "Vercel"],
    year: "2026",
    demoUrl: "https://no-code-adventure-game.vercel.app",
    githubUrl: "https://github.com/F1lmw8/No-Code-Adventure-game",
  },
  {
    id: "project-photolio",
    title: "FLONGF1LM Photolio",
    category: "web",
    categoryLabel: { th: "เว็บแอป", en: "Web App" },
    image: "assets/images/covers/photolio.svg",
    description: {
      th: "เว็บพอร์ตโฟลิโอภาพถ่าย มีแกลเลอรีแบบ lightbox หน้าแอดมินอัปโหลดรูป เก็บรูปบน Cloudinary และอ่านข้อมูล EXIF อัตโนมัติ",
      en: "Personal photography portfolio with a lightbox gallery, admin upload dashboard, Cloudinary image storage, and automatic EXIF extraction.",
    },
    fullDescription: {
      th: "เว็บพอร์ตโฟลิโอภาพถ่ายด้วย Next.js App Router, TypeScript และ TailwindCSS มีแกลเลอรีดูภาพแบบ lightbox ป้องกันการคัดลอกรูปและใส่ลายน้ำได้ พร้อมหน้าแอดมิน (มี login middleware) สำหรับอัปโหลด จัดการ และลบรูป เก็บรูปบน Cloudinary ข้อมูลใน PostgreSQL และอ่านข้อมูลกล้อง (EXIF) อัตโนมัติตอนอัปโหลด",
      en: "A Next.js App Router + TypeScript + TailwindCSS photo portfolio. Includes a public gallery with lightbox viewing, anti-copy overlay and watermark options, plus a protected admin area (login middleware) for uploading, managing, and deleting photos. Images are stored on Cloudinary, metadata in PostgreSQL, and EXIF camera data is read automatically on upload.",
    },
    tags: ["Next.js", "TypeScript", "TailwindCSS", "PostgreSQL", "Cloudinary", "EXIF"],
    year: "2025",
    githubUrl: "https://github.com/F1lmw8/FLONGF1LM",
  },
  {
    id: "project-grpc-movies",
    title: "Movie Microservices with gRPC",
    category: "devops",
    categoryLabel: { th: "Backend & DevOps", en: "Backend & DevOps" },
    image: "assets/images/covers/grpc.svg",
    description: {
      th: "Microservices ภาษา Python 3 ตัว คุยกันผ่าน gRPC และเปิด REST API ด้วย FastAPI รันทั้งหมดด้วย Docker Compose",
      en: "Three Python microservices communicating over gRPC and exposed via FastAPI REST endpoints, all orchestrated with Docker Compose.",
    },
    fullDescription: {
      th: "โปรเจควิชาวิศวกรรมคลาวด์ที่สาธิตการสื่อสารระหว่างเซอร์วิส Service A เป็น gRPC server เก็บข้อมูลหนัง ส่วน Service B และ C เป็นแอป FastAPI ที่ดึงข้อมูลจาก A ผ่าน gRPC แล้วเปิดเป็น REST API ออกแบบโดยนำแนวคิด OOP มาใช้กับ microservices คือ inheritance (ใช้ข้อมูลร่วมจาก A) และ polymorphism (endpoint /my-movie เดียวกันแต่ให้ผลต่างกันตามเซอร์วิส) ทั้งหมดรันใน container ด้วย docker compose",
      en: "A cloud engineering project that demonstrates inter-service communication. Service A is a gRPC server acting as the movie data source; Services B and C are FastAPI apps that fetch data from A over gRPC and expose REST endpoints. The design maps OOP ideas onto microservices — inheritance (shared data from A) and polymorphism (same /my-movie endpoint, different results per service). Everything is containerised and started with docker compose.",
    },
    tags: ["Python", "FastAPI", "gRPC", "Protocol Buffers", "Docker Compose", "Microservices"],
    year: "2026",
  },
  {
    id: "project-cloud-deploy",
    title: "Full-Stack Task App — Cloud Deployment",
    category: "devops",
    categoryLabel: { th: "Full-Stack & Cloud", en: "Full-Stack & Cloud" },
    image: "assets/images/covers/cloud-deploy.svg",
    description: {
      th: "แอปจัดการงานด้วย Express + Prisma + Supabase และหน้าบ้าน Quasar/Vue ทำเป็น Docker และ deploy ขึ้น Render (API) กับ Netlify (หน้าเว็บ)",
      en: "Task manager built with Express + Prisma + Supabase and a Quasar/Vue frontend, Dockerised and deployed to Render (API) and Netlify (SPA).",
    },
    fullDescription: {
      th: "โปรเจค deploy แอป full-stack ครบวงจร หลังบ้านเป็น REST API ด้วย Express.js (CORS, Helmet, Morgan) ใช้ Prisma ORM กับฐานข้อมูล PostgreSQL บน Supabase หน้าบ้านเป็น SPA ด้วย Quasar (Vue 3 Composition API) แสดงวันที่แบบ พ.ศ. มี Dockerfile ทั้งสองฝั่ง docker compose แยก staging/production และ nginx สำหรับหน้าเว็บ",
      en: "An end-to-end full-stack deployment project. The backend is an Express.js REST API (CORS, Helmet, Morgan) using Prisma ORM with a Supabase PostgreSQL database; the frontend is a Quasar (Vue 3 Composition API) SPA with Thai date formatting. Both sides have Dockerfiles, with separate staging / production compose files and an nginx config for the frontend.",
    },
    tags: ["Express", "Prisma", "Supabase", "Quasar", "Vue 3", "Docker", "Render", "Netlify"],
    year: "2026",
    githubUrl: "https://github.com/F1lmw8/lab_4_supabase_fronted_backend",
  },
];

const SKILLS_DATA = [
  { name: "JavaScript / TypeScript", category: "frontend", icon: "code-2", level: 95 },
  { name: "React / Next.js", category: "frontend", icon: "atom", level: 90 },
  { name: "HTML5 / CSS3", category: "frontend", icon: "layout", level: 95 },
  { name: "LINE LIFF & Messaging API", category: "frontend", icon: "message-square", level: 92 },
  { name: "Node.js / Express / Python", category: "backend", icon: "server", level: 88 },
  { name: "FastAPI / REST / GraphQL", category: "backend", icon: "database", level: 85 },
  { name: "Supabase / PostgreSQL / Redis", category: "backend", icon: "hard-drive", level: 88 },
  { name: "LLMs / Agentic AI Systems", category: "ai", icon: "brain", level: 88 },
  { name: "Docker / Docker Compose / gRPC", category: "tools", icon: "container", level: 85 },
  { name: "Vue 3 / Quasar", category: "frontend", icon: "layout-template", level: 85 },
  { name: "Git / GitHub / CI/CD", category: "tools", icon: "git-branch", level: 92 },
  { name: "Vercel / Cloud Infrastructure", category: "tools", icon: "cloud", level: 90 },
];
